AWSTemplateFormatVersion: 2010-09-09

Description: This template create an RDS database 
  

Metadata:
  

Parameters:
  ExportVpcStackName:
    Description: The name of the vpc stack that exports values
    Type: String

  DatabaseInstanceIdentifier:
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
    ConstraintDescription: Must begin with letter and contain only alpanumeric
    Default: mysqldb
    Description: Instance identifier name
    MaxLength: 60
    MinLength: 1
    Type: String

  DatabaseName:
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
    ConstraintDescription: Must begin with letter and contain only alpanumeric
    Default: applicationdb
    Description: MySQL database name
    MaxLength: 64
    MinLength: 1
    Type: String

  DatabaseUser:
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
    ConstraintDescription: Must begin with letter and contain only alpanumeric
    Default: abadmin
    Description: Username for MySQL database access
    MaxLength: 16
    MinLength: 1
    NoEcho: true
    Type: String

  DatabasePassword:
    AllowedPattern: '[a-zA-Z0-9]*'
    ConstraintDescription: Must contain only alphanumeric characters
    Default: Test123
    Description: Password for MySQL database access
    MaxLength: 41
    MinLength: 6
    NoEcho: true
    Type: String

  DatabaseBackupRetentionPeriod:
    ConstraintDescription: Database backup retemtion perios must be between 0 and 35
    Default: 0
    Description:  The number of days for which automatic snapshots
    MaxValue: 35
    MinValue: 0
    Type: Number

  DatabaseAllocatedStorage:
    ConstraintDescription: Must be between 5 and 1024Gb
    Default: 20
    Description: The size of the database (Gb)
    MaxValue: 1024
    MinValue: 5
    Type: Number

  DatabaseInstanceClass:
    AllowedValues:
      - db.t1.micro
      - db.t2.micro
      - db.m1.small
      - db.m1.medium
      - db.m1.large
    ConstraintDescription:
    Default:
    Description:
    Type:

  MultiAZDatabase:
    AllowedValues:
      - true
      - false
    ConstraintDescription: 
    Default:
    Description:
    Type:  


Resources:
 


